services:
  web:
    build: .
    ports:
      - "5000:5000"
    env_file:
      - ./.env
    depends_on:
      - db
    networks:
      - app-network
    restart: always
    command: python app.py

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    env_file:
      - ./.env  # Cargar explícitamente desde .env
    volumes:
      - mysql_data:/var/lib/mysql
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - app-network
    restart: always


networks:
  app-network:
    driver: bridge

volumes:
  mysql_data: